--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: angular-frontend
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: flexi-frontend
  template: 
    metadata: 
      labels: 
        app: flexi-frontend
    spec: 
      containers: 
        - 
          image: "madaan/angular:latest"
          imagePullPolicy: Always
          name: flexi-frontend
          ports: 
            - 
              containerPort: 80
              name: http
