Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@madaann 
madaann
/
Weather-Report-and-AngularUniversal-SSR
Public
forked from Shashidharpatil96/Weather-Report-and-AngularUniversal-SSR
0
11
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Weather-Report-and-AngularUniversal-SSR/flexi-angular.yml
@madaann
madaann Add files via upload
Latest commit 5585930 on Dec 2, 2020
 History
 1 contributor
35 lines (35 sloc)  655 Bytes
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1
  selector:
     matchLabels:
        app: flexi-frontend
  template:
    metadata:
      labels:
        app: flexi-frontend
    spec:
      containers:
      - name: flexi-frontend
        image: madaan/angular:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80       
---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flexi-frontend
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete